[package]
name = "greentic-runner-tests"
version.workspace = true
edition.workspace = true
publish = false

[dev-dependencies]
anyhow.workspace = true
async-trait.workspace = true
greentic-config-types.workspace = true
greentic-flow.workspace = true
greentic-runner-host.workspace = true
greentic-types.workspace = true
jsonschema.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
runner-core.workspace = true
semver.workspace = true
serde_json.workspace = true
serial_test.workspace = true
tempfile.workspace = true
tokio.workspace = true
zip.workspace = true
