[package]
name = "greentic-host"
version.workspace = true
edition = "2021"
license = "MIT"
description = "Wasm pack runner for Greentic agent flows with MCP, telemetry, and adapter support."
repository = "https://github.com/greentic-ai/greentic-runner"
homepage = "https://github.com/greentic-ai/greentic-runner"
documentation = "https://docs.rs/greentic-host"
readme = "../../README.md"
keywords = ["greentic", "runner", "agent", "wasm", "mcp"]
categories = ["wasm", "command-line-utilities", "network-programming"]

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
greentic-flow.workspace = true
greentic-interfaces.workspace = true
greentic-mcp.workspace = true
greentic-telemetry.workspace = true
hex.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_bw.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasmparser.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
chrono.workspace = true
cron.workspace = true
lru.workspace = true
