[package]
name = "component-v0-6-dummy"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.91"
description = "Greentic component component-v0-6-dummy"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.greentic]
abi_version = "0.6.0"

[package.metadata.component]
package = "greentic:component"

[package.metadata.component.target]
world = "greentic:component/component@0.6.0"

[dependencies]
greentic-interfaces-guest = { workspace = true, features = ["component-v0-6"] }
greentic-types = { workspace = true, default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
wit-bindgen = { workspace = true, features = ["macros"] }

[build-dependencies]
greentic-types = { workspace = true, default-features = false }
serde_json = { workspace = true }
